<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,2,1,'svrGt9W5yr4=');
$cfg_Cs[2]=array(0,1,1,'0MLOxdbQ0MQ=');
$cfg_Cs[15]=array(1,2,1,'usy5yMDg');
$cfg_Cs[6]=array(1,2,0,'y66y+sDg');
$cfg_Cs[7]=array(0,1,1,'udjT2s7Sw8c=');
$cfg_Cs[8]=array(0,1,1,'warPtc7Sw8c=');
$cfg_Cs[9]=array(2,1,1,'uavLvtDCzsU=');
$cfg_Cs[10]=array(2,1,1,'0NDStdDCzsU=');
$cfg_Cs[13]=array(0,1,1,'t/7O8dbQ0MQ=');
$cfg_Cs[16]=array(1,2,1,'vNLH3cDg');
?>