<div class="post blog-post blog-post-classic col-lg-12 col-md-12 col-sm-12">
						<div class="blog-post-list">
							<div class="blog-post-meta">
								<span class="post-date">
								<span class="post-day">[field:pubdate function=MyDate('d',@me)'/]</span><br/>
								[field:pubdate function=MyDate('Y-m',@me)'/]</span>
								<span class="post-format">
								<span class="document-icon"></span>
								</span>
								
							</div>
							<div class="blog-post-content">
								<!-- Post Image -->
								<div class="post-thumbnail">
									<img src="[field:picname/]" alt="[field:fulltitle/]" height="200" style="height:200px"/>
									<div class="post-hover">
										<a class="link-icon" href="[field:arcurl /]"></a>
										<a class="search-icon prettyPhoto" href="[field:picname/]"></a>
									</div>
								</div>
								<!-- /Post Image -->
								<!-- Post Content -->
								<div class="post-content">
									
									<h4><a href="[field:arcurl /]" >[field:title/]</a></h4>
									[field:infos /] <a class="read-more big" title="Single Blog Post" href="[field:arcurl /]">查看更多</a>
								</div>
								<!-- /Post Content -->
							</div>
						</div>
					</div>
					<!-- /Post Item -->