<?php
$z[0]=Array("pubdate","",216,258);
$z[0][4]['function']="MyDate('d',@me)'";
$z[1]=Array("pubdate","",280,324);
$z[1][4]['function']="MyDate('Y-m',@me)'";
$z[2]=Array("picname","",582,598);
$z[3]=Array("fulltitle","",605,623);
$z[4]=Array("arcurl","",734,750);
$z[5]=Array("picname","",809,825);
$z[6]=Array("arcurl","",996,1012);
$z[7]=Array("title","",1015,1029);
$z[8]=Array("infos","",1049,1064);
$z[9]=Array("arcurl","",1121,1137);

?>