<?php
$z[0]=Array("field","",446,465);
$z[0][4]['name']="title";
$z[1]=Array("global","",466,492);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",533,562);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",602,660);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3225,3260);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",22277,22314);
$z[5][4]['filename']="footer.htm";

?>