<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/160228/1-16022R32236.jpg ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/160228/1-16022R32236.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="800";
$z[1][4]['height']="860";
$z[2]=Array("img"," /uploads/allimg/160228/1-16022R32236-50.jpg ",240,392);
$z[2][4]['ddimg']="/uploads/allimg/160228/1-16022R32236-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="800";
$z[2][4]['height']="1254";

?>