<div class="col-lg-3 col-md-3 col-sm-6">
                  <div class="project">
                    <div class="project-image wow animated fadeInLeft"> <img src="[field:picname/]" alt="[field:fulltitle/]" height="250" style="height:250px;"/>
                      <div class="project-hover"> <a class="link-icon" href="[field:arcurl /]"></a> <a class="search-icon prettyPhoto" href="[field:picname/]"></a> </div>
                    </div>
                    <div class="project-meta wow animated fadeInLeft" data-wow-offset="0">
                      <h4>[field:title/]</h4>
                      <span class="project-category">[field:infos /]</span>
                      <div class="project-like" data-post="3820"> <i class=" icons icon-heart-7"></i> <span class="like-count">[field:click/]</span> </div>
                    </div>
                  </div>
                </div>