<div class="col-lg-4 col-md-4 col-sm-6 project-item mix category-print">
						<div class="project">
							<div class="project-image">
								<img src="[field:picname/]" alt="[field:fulltitle/]" height="250" style="height:250px"/>
								<div class="project-hover">
									<a class="link-icon" href="[field:arcurl /]"></a>
									<a class="search-icon prettyPhoto" href="[field:picname/]"></a>
								</div>
							</div>
							<div class="project-meta">
								<h4>[field:title/]</h4>
								<span class="project-category">[field:pubdate function=MyDate('Y-m-d',@me)'/]</span>
								<div class="project-like" data-post="3820">
									<i class=" icons icon-heart-7"></i>
									<span class="like-count">[field:click/]</span>
								</div>
							</div>
						</div>
					</div>