<?php
$z[0]=Array("arclist","\r\n            <div class=\"blog-post\"> <span class=\"post-meta\">[field:pubdate function=MyDate('Y-m-d',@me)'/]</span> <a class=\"post-title\" href=\"[field:arcurl /]\">[field:title/]</a>\r\n              <p> [field:infos /] </p>\r\n            </div>\r\n            ",896,1225);
$z[0][4]['titlelen']="40";
$z[0][4]['row']="2";
$z[0][4]['typeid']="9";
$z[0][4]['infolen']="40";
$z[1]=Array("global","",1524,1550);
$z[1][4]['name']="moke_adress";
$z[2]=Array("global","",1614,1634);
$z[2][4]['name']="phone";
$z[3]=Array("global","",1696,1716);
$z[3][4]['name']="email";
$z[4]=Array("global","",1779,1803);
$z[4][4]['name']="cfg_beian";
$z[5]=Array("global","",3920,3946);
$z[5][4]['name']="cfg_powerby";

?>