<?php
$z[0]=Array("field","",446,465);
$z[0][4]['name']="title";
$z[1]=Array("global","",466,492);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",533,562);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",602,660);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3225,3260);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",3634,3664);
$z[5][4]['name']="typename";
$z[6]=Array("field","",3793,3822);
$z[6][4]['name']="position";
$z[7]=Array("channel","\r\n      <div class=\"filter\"><a href='[field:typeurl/]'>[field:typename/]</a></div>\r\n      ",4011,4141);
$z[7][4]['type']="son";
$z[8]=Array("list","\r\n					<div class=\"col-lg-4 col-md-4 col-sm-6 project-item mix category-print\">\r\n						<div class=\"project\">\r\n							<div class=\"project-image\">\r\n								<img src=\"[field:picname/]\" alt=\"[field:fulltitle/]\" height=\"250\" style=\"height:250px\"/>\r\n								<div class=\"project-hover\">\r\n									<a class=\"link-icon\" href=\"[field:arcurl /]\"></a>\r\n									<a class=\"search-icon prettyPhoto\" href=\"[field:picname/]\"></a>\r\n								</div>\r\n							</div>\r\n							<div class=\"project-meta\">\r\n								<h4>[field:title/]</h4>\r\n								<span class=\"project-category\">[field:pubdate function=MyDate('Y-m-d',@me)'/]</span>\r\n								<div class=\"project-like\" data-post=\"3820\">\r\n									<i class=\" icons icon-heart-7\"></i>\r\n									<span class=\"like-count\">[field:click/]</span>\r\n								</div>\r\n							</div>\r\n						</div>\r\n					</div>\r\n                     ",4299,5206);
$z[8][4]['pagesize']="9";
$z[8][4]['titlelen']="30";
$z[8][4]['infolen']="180";
$z[9]=Array("pagelist","",5358,5429);
$z[9][4]['listitem']="info,index,end,pre,next,pageno";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",5588,5625);
$z[10][4]['filename']="footer.htm";

?>