<?php
$z[0]=Array("field","",446,465);
$z[0][4]['name']="title";
$z[1]=Array("global","",466,492);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",533,562);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",602,660);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3225,3260);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",3566,3596);
$z[5][4]['name']="typename";
$z[6]=Array("field","",3725,3754);
$z[6][4]['name']="position";
$z[7]=Array("arclist","\r\n				<div class=\"accordion accordion-active\">\r\n					<div class=\"accordion-header\">\r\n						<div class=\"accordion-icon\">\r\n						</div>\r\n						<h5>[field:title/]</h5>\r\n					</div>\r\n					<div class=\"accordion-content display-block\">\r\n						<p>\r\n							[field:infos /]...<a href=\"[field:arcurl /]\" target=\"_blank\">[ÏêÇé]</a>\r\n						</p>\r\n						\r\n					</div>\r\n				</div>\r\n			 ",13192,13644);
$z[7][4]['titlelen']="100";
$z[7][4]['limit']="0,1";
$z[7][4]['typeid']="4";
$z[7][4]['infolen']="220";
$z[8]=Array("arclist","\r\n				<div class=\"accordion\">\r\n					<div class=\"accordion-header\">\r\n						<div class=\"accordion-icon\">\r\n						</div>\r\n						<h5>[field:title/]</h5>\r\n					</div>\r\n					<div class=\"accordion-content display-block\">\r\n						<p>\r\n							[field:infos /]...<a href=\"[field:arcurl /]\" target=\"_blank\">[ÏêÇé]</a>\r\n						</p>\r\n						\r\n					</div>\r\n				</div>\r\n			 ",13660,14095);
$z[8][4]['titlelen']="100";
$z[8][4]['limit']="1,2";
$z[8][4]['typeid']="4";
$z[8][4]['infolen']="220";
$z[9]=Array("include","",16078,16115);
$z[9][4]['filename']="footer.htm";

?>